name: test3
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  contacts_service: ^0.3.9
  permission_handler: ^4.0.0
  spinner_input: ^0.1.2
  datetime_picker_formfield: ^0.4.3
  font_awesome_flutter: ^8.5.0
  provider: ^3.1.0
  transformer_page_view: ^0.1.6
  image_picker: ^0.6.2+3
  flushbar: ^1.9.1
  intl: ^0.15.5
  flutter_native_timezone: ^1.0.2
  timezone: ^0.5.2
  simple_gesture_detector: ^0.1.3
  flutter_launcher_icons: ^0.7.2+1
  geolocator: ^5.1.5
  firebase_storage: ^2.1.0+1
  synchronized: ^2.1.1



flutter_icons:    
 android: "launcher_icon"    
 ios: true    
 image_path: "Assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - Assets/anton.jpg
    - Assets/photo-1512152272829-e3139592d56f.jpeg
    - Assets/golf.jpg
    - Assets/hotel.jpg
    - Assets/polo.jpg
    - Assets/restaurant.jpg
    - Assets/spa.jpg
    - Assets/wine.jpg
    - Assets/vdv.png
    - Assets/images/
    - Assets/Val-De-Vie-Aerial-20-1024x575.jpg.jpeg
    - Assets/vdvLogo2.png
    - Assets/Sunset-001-1024x682.jpg.jpeg
    - Assets/61htWk5w.jpg
    - Assets/poloR.jpg
    - Assets/valleyR.jpg
    - Assets/CoffieR.jpg
    - Assets/wineR.jpg
    - Assets/golfR.jpg
    - Assets/golfRP.jpg
    - Assets/SPAr.jpeg
    - Assets/poloA.jpg
    - Assets/ridingSchool.jpg
    - Assets/Competitive.jpg
    - Assets/4BWK9bCw.jpeg
    - Assets/tennis.jpg
    - Assets/hotelr.jpg
    - Assets/vLogo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
